### ISSUE TITLE
Cannot select files when importing

### ISSUE THREAD

**Issue by mostafaroshdy1** [ente-io/ente#4991]
### Description

i would like to point to this  [issue](https://github.com/flathub/io.ente.auth/issues/10) which makes the app is unusable in linux flatpak version

### Version

4.0.3

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by megusta-01** [comment]
same here

**Comment by kolon0** [comment]
I really love this app, but it's unusable due to this error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1223)
#1      _ButtonChildWidgetState._onTapUp.<anonymous closure> (package:ente_auth/ui/components/buttons/button_widget.dart:511)
#2      new Future.delayed.<anonymous closure> (dart:async/future.dart:431)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```
Additionally, export codes (encrypted) didn’t work for me, giving the same error. It seems like the app struggles to use the portals—I'm not sure. I'm using Fedora Kinoite 41, in case that matters.

**Comment by ua741** [comment]
This should be fixed in the latest version.

**Comment by didli** [comment]
It seems this is still an issue for me for _auth-v4.4.23_ both in the flatpak and appimage versions.

**Comment by ua741** [comment]
@didli can you please share the logs

**Comment by didli** [comment]
My bad : I didn't realize I had an issue with xdg-desktop-portal.service which prevented to select the file.
sorry for the noise. This can remain ... closed ^^´
