### ISSUE TITLE
X (formerly Twitter) icon is black on dark mode, unable to see yet other icons that have dark and light mode variant (if set up properly) is fine. Still not fixed on Stable Ente 4.4.4 and even 4.4.8 Beta.

### ISSUE THREAD

**Issue by BeemoKincaid** [ente-io/ente#7828]
X (formerly Twitter) icon is black on dark mode, unable to see yet other icons that have dark and light mode variant (if set up properly) is fine. Still not fixed on Stable Ente 4.4.4 and even 4.4.8 Beta.

Also a new bug on 4.4.8 Beta, unable to set Auto lock timer to preferred time (i.e. 30 seconds or 1 minute), stuck at default setting: 5 seconds.
![20251108_184811](https://github.com/user-attachments/assets/7f2d8762-d502-4ed8-b19e-5ec2ea739201)
![20251108_184825](https://github.com/user-attachments/assets/ce8ef055-dd84-4082-9e76-a222f63ea691)
https://github.com/user-attachments/assets/fc87692f-5c1c-4071-af95-417e1a90db52

_Originally posted by @BeemoKincaid in https://github.com/ente-io/ente/discussions/7827_

**Comment by mnvr** [comment]
> Also a new bug on 4.4.8 Beta, unable to set Auto lock timer to preferred time (i.e. 30 seconds or 1 minute), stuck at default setting: 5 seconds.

This is fixed in the latest beta (and will also be part of the release too)

**Comment by prateekmedia** [comment]
The "X" icon's theming in auth is fixed in latest beta version: [auth-v4.4.11-beta](https://github.com/ente-io/ente/releases/tag/auth-v4.4.11-beta)

**Comment by Lord-Of-Mysteries404** [comment]
@mnvr @prateekmedia I'm using the latest 4.4.10 stable version tho? And the bug is still present there. It exists from version 4.4.4

**Comment by Lord-Of-Mysteries404** [comment]
@mnvr @prateekmedia it's not just X icon but some other black icons is also showing same issues. Please fix this bug

**Comment by prateekmedia** [comment]
We either have [custom icons](https://github.com/ente-io/ente/tree/main/mobile/apps/auth/assets/custom-icons/icons) or use [simple icons](https://github.com/simple-icons/simple-icons/tree/6dcfdc2f58f6150d7b097b5cab158d27413f6366/icons). If you think it is custom icon issue then you can contribute a fix for that, if it is a simple icon issue then you can report in their repo.

**Comment by Lord-Of-Mysteries404** [comment]
> We either have [custom icons](https://github.com/ente-io/ente/tree/main/mobile/apps/auth/assets/custom-icons/icons) or use [simple icons](https://github.com/simple-icons/simple-icons/tree/6dcfdc2f58f6150d7b097b5cab158d27413f6366/icons). If you think it is custom icon issue then you can contribute a fix for that, if it is a simple icon issue then you can report in their repo.

Well I don't know. But you can see it for yourself if it's a custom icon or simple ones. (Edit: The xAI icon is also disappearing in dark mode)
![20251126_212903.jpg](https://github.com/user-attachments/assets/08587f4c-8109-4a2f-a5ef-8b9bda860486)
![20251126_212914.jpg](https://github.com/user-attachments/assets/a4cccb64-a0ae-4a01-b746-0bedf3c2e636)
![20251128_005955.jpg](https://github.com/user-attachments/assets/7c3f0573-93b1-496e-8bbf-02ec14cb442d)
![20251128_010008.jpg](https://github.com/user-attachments/assets/cb616841-7268-43e7-972c-0e3c5c190b7e)

And as much as I'd like to contribute but I have zero knowledge in coding so Please take care of it.
